### PR TITLE
[WIP] [EDGENT-292] Add mailmap and contributors list

### PR DESCRIPTION
**Pull request by Cazen**
- [ ] If there are contributors missing in the list belows, please reply on this PR. I've find these information from repos(incubator-edgent, incubator-edgent-website) and wiki
- [ ] The streamsadmin account is not clear I'll check it out a little more.

### CODE REVIEW

**Comment by bjhargrave** [comment]
> The streamsadmin account is not clear I'll check it out a little more.

I suspect this is an IBM internal account given the streams name.

**Comment by ddebrunner** [comment]
`streamsadmin` is used as the linux user identifier on the IBM Streams Quickstart VM. Commits may have come from folks using that vm as a development environment.

**Comment by dlaboss** [comment]
Can you also/instead create a PR to merge to the release1.0.0 branch pls. (change the merge-to selection when creating the PR)

**Comment by Cazen** [comment]
@dlaboss Sure :)

**Pull request merged**
