### PR TITLE
Add sensors to Java 7 for Android

### PR DESCRIPTION
**Pull request by ddebrunner**

### CODE REVIEW

**Comment by dlaboss** [comment]
-1

Please update JAVA_SUPPORT.md for analytics/sensors (and anything else you may know of).
As the original author of JAVA_SUPPORT could you also improve that doc to clarify the meaning of a "blank" in a platform column.

If this is desired/required for release1.0.0 can you make the change as a branch/PR off of the release1.0.0 branch?

**Comment by ddebrunner** [comment]
Updated JAVA_SUPPORT.md.
Let me know if you need other changed before lifting the -1.
I'll probably merge to master than then create a merge pr from master to release1.0.0

**Comment by ddebrunner** [comment]
@dlaboss ping!

**Comment by dlaboss** [comment]
+1

**Pull request merged**
