### PR TITLE
[EDGENT-168] Console: Fix missing source/target stream tags

### PR DESCRIPTION
**Pull request by queeniema**

### CODE REVIEW

**Comment by queeniema** [comment]
@dlaboss, if a stream has multiple tags, all of the tags will appear in the table cell. If there are multiple streams, each with multiple tags, then all of the tags associated with the streams wll be displayed. I attached images to the JIRA issue.

**Comment by dlaboss** [comment]
I see the ci failure was an unrelated failure of WindowsTest.  I just now merged a PR for that test that @wmarshall484 created a while ago so hopefully this one wont bother us anymore.

**Comment by queeniema** [comment]
Thank you, @dlaboss! I'll close and reopen this PR to run the CI build once more.

**Comment by dlaboss** [comment]
Sigh.. this ci failure was on the java7 run of HttpGlobalTest (part of test7.run target).  All of java8 build/test/release processing prior to that were successful.  As that test uses the public http://httpbin.org web-server, maybe there was just a hickup with it. Clearly the changes in this PR have nothing to do with that so IMO don't feel compelled to await a clean ci run before merging.

**Comment by queeniema** [comment]
Thanks @dlaboss, I'll go ahead and merge this one in then.

**Pull request merged**
